export const ADD_AGENDA = 'ADD_AGENDA'
export const EDIT_AGENDA = 'EDIT_AGENDA'
export const TOGGLE_AGENDA = 'TOGGLE_AGENDA'
export const COMPLETE_AGENDA = 'COMPLETE_AGENDA'
export const REMOVE_AGENDA = 'REMOVE_AGENDA'

export const ADD_TASK = 'ADD_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const TOGGLE_TASK = 'TOGGLE_TASK'
export const COMPLETE_TASK = 'COMPLETE_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
