export const ADD_AGENDA = 'ADD_AGENDA'
export const EDIT_AGENDA = 'EDIT_AGENDA'
export const TOGGLE_AGENDA = 'TOGGLE_AGENDA'
export const COMPLETE_AGENDA = 'COMPLETE_AGENDA'
export const REMOVE_AGENDA = 'REMOVE_AGENDA'

export const FETCH_AGENDAS = 'FETCH_AGENDAS'
export const REQUEST_AGENDAS = 'REQUEST_AGENDAS'
export const RECEIVE_AGENDAS = 'RECEIVE_AGENDAS'

export const SELECT_AGENDA = 'SELECT_AGENDA'
export const INVALIDATE_AGENDA = 'INVALIDATE_AGENDA'

export const ADD_TASK = 'ADD_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const TOGGLE_TASK = 'TOGGLE_TASK'
export const COMPLETE_TASK = 'COMPLETE_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'

export const REQUEST_TASKS = 'REQUEST_TASKS'
export const RECEIVE_TASKS = 'RECEIVE_TASKS'
